wget https://github.com/demo2099/jd_jscripts/raw/master/jd_bean_change.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_syj.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_blueCoin.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_bookshop.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_car_exchange.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_cash.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_cfd.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jx_sign.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_crazy_joy_bonus.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_crazy_joy_coin.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_jdfactory.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_family.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_fruit.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_get_share_code.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_global.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_global_mh.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_shop.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_joy.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_joy_feedPets.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_joy_reward.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_joy_run.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_jxd.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_jxnc.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_live.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_live_redrain.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_mohe.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_moneyTree.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_necklace.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_nzmh.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_pet.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_pigPet.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_plantBean.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_price.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_redPacket.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_sgmh.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_small_home.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_speed_sign.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_superMarket.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_unsubscribe.js
wget https://github.com/demo2099/jd_jscripts/raw/master/backUp/xmSports.js
wget https://github.com/demo2099/jd_jscripts/raw/master/jd_speed.js
